cyclonejet/models/__init__.py
from cyclonejet.models.votes import Vote, AnimeVote
from cyclonejet.models.anime import Anime
from cyclonejet.models.users import User, Profile, Group
from cyclonejet.models.manga import Manga

cyclonejet/models/anime.py
import datetime
from cyclonejet.extensions import db
from cyclonejet.models.users import User

class Anime(db.Model):
    
    __tablename__ = 'anime'
    
    id = db.Column(db.Integer, primary_key=True)
    
    title = db.Column(db.Unicode(250), unique=True)
    created = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    description = db.Column(db.UnicodeText)
   
    #genres ?
    #type? (series,ova,movie)

    uploader_id = db.Column(db.Integer, db.ForeignKey(User.id))
    uploader = db.relationship(User, backref='animes')

    def __init__(self, title, description=None):
        self.title = title
        if description:
            self.description = description

    def __repr__(self):
        return '<Anime: %r>' % self.title

#class Episode(db.Model):
# many episodes -> one anime

cyclonejet/models/manga.py
import datetime
from cyclonejet.extensions import db
from cyclonejet.models.users import User

class Manga(db.Model):

    __tablename__ = 'manga'

    id = db.Column(db.Integer, primary_key=True)

    title = db.Column(db.Unicode(250), unique=True, nullable=False)
    created = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    description = db.Column(db.UnicodeText)

    year = db.Column(db.String(10))
    author = db.Column(db.Unicode(250))

    uploader_id = db.Column(db.Integer, db.ForeignKey(User.id))
    uploader = db.relationship(User, backref='mangas')

    def __init__(self, title, description=None, year=None, author=None):
        self.title = title
        self.description = description
        self.year = year
        self.author = author

    def __repr__(self):
        return '<Manga: %r>' % self.title

#class Chapter(db.Model):
#    
#    many chapters -> one manga

cyclonejet/models/users.py
import datetime
from cyclonejet.extensions import db, mail

from werkzeug import generate_password_hash, check_password_hash

from flaskext.sqlalchemy import BaseQuery
from flaskext.mail import Message

groups = db.Table('groups', 
        db.Column('group_id', db.Integer, db.ForeignKey('group.id')),
        db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
)

class UserQuery(BaseQuery):

    @staticmethod
    def create_user(username, email, password, admin=False):
        if admin:
            user = User.query.filter_by(role=User.ADMIN).first()
        else:
            user = User.query.filter_by(username=username).first()
        
        if not user:
            user = User(username, email, password)
            if admin:
                user.role = User.ADMIN
            db.session.add(user)
            db.session.commit()
        return user


class User(db.Model):
    # A user.

    MEMBER = 1
    ADMIN = 2

    query_class = UserQuery

    id = db.Column(db.Integer, primary_key=True)
    
    username = db.Column(db.Unicode(60), unique=True, nullable=False)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(150))

    groups = db.relationship('Group', secondary=groups, backref=db.backref('users'))

    role = db.Column(db.Integer, default=MEMBER)

    created = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    profile = db.relationship('Profile', uselist=False, backref='user')

    is_verified = db.Column(db.Boolean, default=False)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.set_password(password)


    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        if password:
            return check_password_hash(self.password, password)

    def change_password(self, new_password, old_password=None):
        if old_password:
            if not self.check_password(old_password): 
                return False

        self.set_password(new_password)

    def send_mail(self, subject, message):
        msg = Message(
            subject,
            recipients = [self.email],
            body = message,
            #sender is DEFAULT_MAIL_SENDER
        )
        mail.send(msg)

    def join_group(self, group):
        self.groups.append(group)

    def leave_group(self, group):
        self.groups.remove(group)

    def is_admin(self):
        if self.role == 2:
            return True

    def __repr__(self):
        return '<User: %r>' % self.username


class Profile(db.Model):
    # A user has a profile
    
    id = db.Column(db.Integer, primary_key=True)
   
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    reputation = db.Column(db.Integer)
    gravatar = db.Column(db.String(250)) #gravatar url

    created = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def __init__(self, user):
        self.user_id = user.id

    def __repr__(self):
        return '<Profile: %r>' % self.user.username


class Group(db.Model):
    # A user can belong to multiple groups.
    
    id = db.Column(db.Integer, primary_key=True)
    
    name = db.Column(db.Unicode(250), unique=True, nullable=False)
    created = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<UserGroup: %r>' % self.name

cyclonejet/models/votes.py
from cyclonejet.extensions import db
from cyclonejet.models.users import User
from cyclonejet.models.anime import Anime
from cyclonejet.models.manga import Manga

class Vote(db.Model):

    id = db.Column('id', db.Integer, primary_key=True)
    discriminator = db.Column('type', db.String(50))
    __mapper_args__ = {'polymorphic_on': discriminator}

    score = db.Column('score', db.Float)

    user_id = db.Column('user_id', db.Integer, db.ForeignKey(User.id))
    user = db.relationship(User, backref='votes')

    def __init__(self, score, user):
        self.score = score
        self.user = user

    def __repr__(self):
        return '<Vote: %r - %r>' % (self.discriminator, self.user.username)

class AnimeVote(Vote):
    __mapper_args__ = {'polymorphic_identity': 'animevote'}

    anime_id = db.Column(db.Integer, db.ForeignKey(Anime.id))
    anime = db.relationship(Anime, backref='votes')

    def __init__(self, score, user, anime):
        super(AnimeVote, self).__init__(score, user)
        self.anime = anime

class MangaVote(Vote):
    __mapper_args__ = {'polymorphic_identity': 'mangavote'}

    manga_id = db.Column(db.Integer, db.ForeignKey(Manga.id))
    manga = db.relationship(Manga, backref='votes')

    def __init__(self, score, user, manga):
        super(MangaVote, self).__init__(score, user)
        self.manga = manga

cyclonejet/forms/__init__.py
from cyclonejet.forms.registration import RegistrationForm
from cyclonejet.forms.login import LoginForm

cyclonejet/forms/login.py
from flaskext.wtf import Form, TextField, PasswordField, validators

class LoginForm(Form):
    username = TextField(u"Username", validators=[validators.Required()])
    password = PasswordField(u"Password", validators=[validators.Required()]) 

cyclonejet/forms/registration.py
from flaskext.wtf import Form, TextField, PasswordField, validators, ValidationError
from cyclonejet.models import User

class RegistrationForm(Form):

    username = TextField(u"Username", validators=[validators.Required(), validators.Length(min=2)])
    email = TextField(u"Email", validators=[validators.Required(), validators.Email()])
    password = PasswordField(u"Password", validators=[validators.Required()])

    def validate_username(self, field):
        user = User.query.filter_by(username=field.data).first()
        if user:
            raise ValidationError("This username already exists.")

    def validate_email(self, field):
        user = User.query.filter_by(email=field.data).first()
        if user:
            raise ValidationError("This email already exists for a user.")

cyclonejet/__init__.py
# -*- encoding:utf-8 -*-
from cyclonejet.app import create_app

cyclonejet/app.py
from flask import Flask, render_template
from cyclonejet.views.frontend import frontend
from cyclonejet.views.anime import anime
from cyclonejet.views.manga import manga
from cyclonejet.views.accounts import accounts

from cyclonejet.extensions import db
from cyclonejet.extensions import mail

from cyclonejet.config import Config

def create_app(name):
    app = Flask(name)
    
    app.config.from_object(Config)

    #Blueprint registration
    app.register_blueprint(frontend)
    app.register_blueprint(accounts)
    app.register_blueprint(anime, url_prefix='/anime')
    app.register_blueprint(manga, url_prefix='/manga')

    #DB intialization
    db.init_app(app)
    
    #Mail initialization
    mail.init_app(app)

    #Custom Error handling (move this somewhere else?)
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    return app

cyclonejet/views/__init__.py
# -*- encoding:utf-8 -*-

cyclonejet/views/accounts.py
from flask import Blueprint, url_for, redirect, flash, request, render_template, session
from cyclonejet.forms import RegistrationForm, LoginForm
from cyclonejet.models.users import User

from cyclonejet.views.utils import login_required, login_user, logout_user

accounts = Blueprint('accounts', __name__)

@accounts.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegistrationForm(request.form)

    if request.method == 'POST' and form.validate():
        user = User.query_class.create_user(
                username = form.username.data,
                email= form.email.data,
                password = form.password.data
        )
        # send verification email
        user.send_mail(
            subject = "[cyclonejet] You've just signed up!",
            message = """Thank you for registering to cyclonejet [verification link here]"""
        )

        #log user in automatically
        login_user(user)

        flash("%s registered successfully!" % user.username)
        return redirect(url_for('accounts.profile'))
    
    return render_template('register.html', form=form)

@accounts.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)

    if request.method == 'POST' and form.validate():
        user = User.query.filter_by(username=form.username.data).first()

        if not user:
            flash('This user is not registered')
        elif not user.check_password(form.password.data):
            flash('Incorrect password')
        else:
            flash("You've been logged in")
            login_user(user)
            return redirect(url_for('accounts.profile'))

    return render_template('login.html', form=form)

@accounts.route('/logout/')
@login_required
def logout():
    logout_user()
    flash("You've been logged out, see ya")
    return redirect(url_for('frontend.index'))

@accounts.route('/profile/')
@login_required
def profile():
    user = User.query.get(session['uid'])
    return render_template('profile.html', user=user)

cyclonejet/views/anime.py
# -*- encoding:utf-8 -*-
from flask import Blueprint, request, render_template, session, jsonify, redirect, url_for
from cyclonejet.models.anime import Anime
from cyclonejet.models.votes import AnimeVote
from cyclonejet.models.users import User
from cyclonejet.views.generic import PaginatedListView
from cyclonejet.views.utils import login_required

from cyclonejet.extensions import db

anime = Blueprint('anime', __name__)

index = PaginatedListView.as_view('anime_list', template_name='anime/list.html', model=Anime)

def detail(anime_id):
    anime = Anime.query.get_or_404(anime_id)
    return render_template('anime/detail.html', anime=anime)

@login_required
def vote(anime_id):
  
    #expect ajax request
    if request.is_xhr:
        if request.method == 'POST' and 'score' in request.form:
    
            user = User.query.get(session['uid']) 
            anime = Anime.query.get_or_404(anime_id)
            score = request.form.get('score', 0, type=float)
            vote = AnimeVote(
                score = score,
                user = user,
                anime= anime
            )
            db.session.add(vote)
            db.session.commit()

            return jsonify(success=True, score=score)

    else:
        return redirect(url_for('anime.detail', anime_id=anime_id))
vote.methods = ['POST']

anime.add_url_rule('/', 'index', view_func=index)
anime.add_url_rule('/<int:anime_id>/', 'detail', view_func=detail)
anime.add_url_rule('/<int:anime_id>/vote/', 'vote', view_func=vote)

cyclonejet/views/frontend.py
# -*- encoding:utf-8 -*-
from flask import Blueprint, render_template

frontend = Blueprint('frontend', __name__)

@frontend.route('/')
def index():
    return render_template('index.html')

cyclonejet/views/generic.py
from flask.views import View
from flask import request, render_template, abort


class ListView(View):

    def __init__(self, template_name):
        self.template_name = template_name

    def render_template(self, context):
        return render_template(self.template_name, **context) #unpack context
    
    def get_context(self):
        """Should return a dictionary."""
        raise NotImplementedError()

    def dispatch_request(self):
        context = {}
        context.update(self.get_context())
        return self.render_template(context)


class PaginatedListView(ListView):
    
    methods = ['GET']

    def __init__(self, model, template_name, paginate_by=25):
        self.model = model
        self.ctype = self.model.__name__.lower()
        self.template_name = template_name
        self.paginate_by = paginate_by

    def paginate(self):
        ctxt = {'type': self.ctype}

        page = int(request.args.get('p', 1))
        
        obj_count = self.model.query.count()
        num_pages = obj_count / self.paginate_by

        if not obj_count: #we can't do anything without objects
            ctxt['error'] = "There are no '%s' in the database, make sure to add some." % self.ctype
            return ctxt

        if obj_count % self.paginate_by > 0:
            num_pages += 1

        if page < 1 or page > num_pages:
            return abort(404)
       
        objects = self.model.query.order_by('title').limit(self.paginate_by).offset((page - 1) * self.paginate_by)

        ctxt.update({
            'entries' : objects,
            'current_page' : page,
            'num_pages' : num_pages,
        })
        return ctxt
        
    def get_context(self):
        return self.paginate()
        

cyclonejet/views/manga.py
# -*- encoding:utf-8 -*-
from flask import Blueprint, render_template
from cyclonejet.models.manga import Manga
from cyclonejet.views.generic import PaginatedListView

manga = Blueprint('manga', __name__)

index = PaginatedListView.as_view('anime_list', template_name='manga/list.html', model=Manga)

def detail(manga_id):
    manga = Manga.query.get_or_404(manga_id)
    return render_template('manga/detail.html', manga=manga)

manga.add_url_rule('/', 'index', view_func=index)
manga.add_url_rule('/<int:manga_id>/', 'detail', view_func=detail)

cyclonejet/views/utils.py
from flask import session, redirect, url_for
from functools import wraps

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'logged_in' not in session or session['logged_in'] is None:
            return redirect(url_for('accounts.login'))
        return f(*args, **kwargs)
    return decorated_function

def login_user(user):
    session['uid'] = user.id
    session['username'] = user.username
    session['logged_in'] = True

def logout_user():
    session.pop('logged_in', None)

cyclonejet/templates/base.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>cyclonejet - {% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width,initial-scale=1">

    {% block css %}
        <link rel="stylesheet" href="/static/css/style.css">
    {% endblock %}

    <script src="/static/js/libs/modernizr-2.0.6.min.js"></script>
</head>

<body class="{% block body_class %}{% endblock %}">
    <div id="container">		
				<header>
						<h1><a href="">cyclonejet</a></h1>

            {% if session['logged_in'] %}
                <p>Welcome {{ session['username'] }}! <a href="{{ url_for('accounts.logout') }}">Logout</a>?</p>
            {% else %}
                <p><a href="{{ url_for('accounts.login') }}">Login</a> or <a href="{{ url_for('accounts.register') }}">Register</a></p>
            {% endif %}
            <nav>
                <ul>
										<li><a class="home" href="{{ url_for('frontend.index') }}">home</a></li>	
										<li><a class="anime" href="{{ url_for('anime.index') }}">anime</a></li>	
										<li><a class="manga" href="{{ url_for('manga.index') }}">manga</a></li>	
                </ul>
            </nav> <!-- end main nav -->
        </header>	

        <div id="main" role="main">
						{% block messages %} 
						<ul class="messages">
						{% for m in get_flashed_messages() %}<li>{{ m }}</li>{% endfor %}
						</ul>
						{% endblock %}
					
						{% block content %} 
						{% endblock %}
        </div> <!-- end main content -->
		
        <footer>
        </footer>
    </div> <!-- end container -->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/static/js/libs/jquery-1.6.2.min.js"><\/script>')</script>
{% block extra %}
<script src='/static/js/site.js'></script>
{% endblock %}
</body>
</html>

cyclonejet/templates/entry-index.html
{% extends 'base.html' %}

{% block title %}{{ type }}{% endblock %}

{% block body_class %}{{ type }}{% endblock %}
{% block content %}
Type {{ type }}
{% if error %}

    <p><strong>{{ error }}</strong></p>
    
{% else %}

    {% for entry in entries %}
        <p>{{ entry.title }} - {{ entry.description }}</p>
    {% endfor %}
    
    {% include 'parts/pagination.html' %}
    
{% endif %}

{% endblock %}

cyclonejet/templates/index.html
{% extends 'base.html' %}

{% block title %}home{% endblock %}

{% block body_class %}home{% endblock %}

{% block content %}

<h1>Someone should code something ... >.></h1>

{% endblock %}

cyclonejet/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

    <form method="post" action="">
        {% for field in form %}

            {% if field.name != 'csrf' %}
                {{ field.label }}
            {% endif %}
            
            {{ field }}
            
            {% if field.errors %}
                <ul class='errors'>
                    {% for error in field.errors %}<li>{{ error }}{% endfor %}
                </ul>
            {% endif %}

        {% endfor %}
        <input type="submit" value="Login">
    </form>

{% endblock %}

cyclonejet/templates/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

	<h2> Welcome to your profile {{ user.username }} </h2>

{% endblock %}

cyclonejet/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}

    <form method="post" action="">
    {% for field in form %}

        {% if field.name == 'csrf' %}
            {# do nothing i.e don't display this label #}
        {% else %}
            {{ field.label }}
        {% endif %}
        
        {{ field }}
        
        {% if field.errors %}
            <ul class='errors'>
                {% for error in field.errors %}<li>{{ error }}{% endfor %}
            </ul>
        {% endif %}

        {% endfor %}
        <input type="submit" value="Sign up!">
    </form>

{% endblock %}